// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package config

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../config/templates", "heroku.yml.plush", "\"YnVpbGQ6CiAgZG9ja2VyOgogICAgd2ViOiBEb2NrZXJmaWxlCjwlPSBpZiAoYXBwLldpdGhQb3ApIHsgJT4KcmVsZWFzZToKICBjb21tYW5kOgogICAgLSAvYmluL2FwcCBtaWdyYXRlCiAgaW1hZ2U6IHdlYgo8JSB9ICU+Cg==\"")
}
